// BibleChantée – Distribution mondiale – Données plateformes V2
// ⚠️ bibleChanteeUrl : à compléter manuellement plateforme par plateforme
// ⚠️ availabilityStatus : à confirmer — valeurs possibles : "live" | "pending" | "unknown" | "not_applicable"
window.distributionData = {
  platforms: [
    // ── SPOTIFY ECOSYSTEM ────────────────────────────────────────────────────────
    {
      id: "spotify",
      name: "Spotify",
      category: "streaming",
      ecosystem: "Spotify ecosystem",
      color: "#1DB954",
      region: "Global",
      lat: 59.3293, lng: 18.0686, city: "Stockholm",
      regions: ["Mondial"],
      icon: "🎵",
      officialUrl: "https://open.spotify.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    // ── APPLE ECOSYSTEM ──────────────────────────────────────────────────────────
    {
      id: "apple-music",
      name: "Apple Music",
      category: "streaming",
      ecosystem: "Apple ecosystem",
      color: "#A2AAAD",
      region: "Global",
      lat: 37.3346, lng: -122.0090, city: "Cupertino",
      regions: ["Mondial"],
      icon: "🍎",
      officialUrl: "https://music.apple.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    {
      id: "itunes",
      name: "iTunes",
      category: "streaming",
      ecosystem: "Apple ecosystem",
      color: "#A2AAAD",
      region: "Global",
      lat: 37.3346, lng: -122.0090, city: "Cupertino",
      regions: ["Mondial"],
      icon: "🍎",
      officialUrl: "https://www.apple.com/itunes/",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    // ── YOUTUBE / GOOGLE ECOSYSTEM ───────────────────────────────────────────────
    {
      id: "youtube-music",
      name: "YouTube Music",
      category: "streaming",
      ecosystem: "YouTube / Google ecosystem",
      color: "#FF0000",
      region: "Global",
      lat: 37.4220, lng: -122.0841, city: "Mountain View",
      regions: ["Mondial"],
      icon: "▶️",
      officialUrl: "https://music.youtube.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    // ── AMAZON ECOSYSTEM ─────────────────────────────────────────────────────────
    {
      id: "amazon-music",
      name: "Amazon Music",
      category: "streaming",
      ecosystem: "Amazon ecosystem",
      color: "#00A8E0",
      region: "Global",
      lat: 47.6062, lng: -122.3321, city: "Seattle",
      regions: ["Mondial"],
      icon: "📦",
      officialUrl: "https://music.amazon.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    // ── AUDIO STREAMING ALTERNATIF ───────────────────────────────────────────────
    {
      id: "deezer",
      name: "Deezer",
      category: "streaming",
      ecosystem: "Alternatif",
      color: "#9B59B6",
      region: "Europe / Global",
      lat: 48.8566, lng: 2.3522, city: "Paris",
      regions: ["Europe", "Monde"],
      icon: "🎧",
      officialUrl: "https://www.deezer.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    {
      id: "tidal",
      name: "Tidal",
      category: "streaming",
      ecosystem: "Alternatif",
      color: "#9B59B6",
      region: "Global",
      lat: 59.9139, lng: 10.7522, city: "Oslo",
      regions: ["Monde"],
      icon: "🎧",
      officialUrl: "https://tidal.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    {
      id: "iheartradio",
      name: "iHeartRadio",
      category: "streaming",
      ecosystem: "Alternatif",
      color: "#9B59B6",
      region: "USA",
      lat: 40.7128, lng: -74.0060, city: "New York",
      regions: ["USA"],
      icon: "📻",
      officialUrl: "https://www.iheart.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    {
      id: "pandora",
      name: "Pandora",
      category: "streaming",
      ecosystem: "Alternatif",
      color: "#9B59B6",
      region: "USA",
      lat: 37.8044, lng: -122.2712, city: "Oakland",
      regions: ["USA"],
      icon: "📻",
      officialUrl: "https://www.pandora.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    {
      id: "qobuz",
      name: "Qobuz",
      category: "streaming",
      ecosystem: "Alternatif",
      color: "#9B59B6",
      region: "Europe",
      lat: 48.8566, lng: 2.3522, city: "Paris",
      regions: ["Europe"],
      icon: "🎧",
      officialUrl: "https://www.qobuz.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    // ── SOCIAL MEDIA ─────────────────────────────────────────────────────────────
    {
      id: "instagram",
      name: "Instagram",
      category: "social",
      ecosystem: "Meta",
      color: "#E91E8C",
      region: "Global",
      lat: 37.4845, lng: -122.1477, city: "Menlo Park",
      regions: ["Mondial"],
      icon: "📸",
      officialUrl: "https://www.instagram.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    {
      id: "facebook",
      name: "Facebook",
      category: "social",
      ecosystem: "Meta",
      color: "#E91E8C",
      region: "Global",
      lat: 37.4845, lng: -122.1477, city: "Menlo Park",
      regions: ["Mondial"],
      icon: "👥",
      officialUrl: "https://www.facebook.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    {
      id: "tiktok",
      name: "TikTok",
      category: "social",
      ecosystem: "ByteDance",
      color: "#E91E8C",
      region: "Global",
      lat: 39.9042, lng: 116.4074, city: "Beijing",
      regions: ["Mondial"],
      icon: "🎵",
      officialUrl: "https://www.tiktok.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    }
  ],
  // ── META ──────────────────────────────────────────────────────────────────────
  categoryMeta: {
    "streaming": { label: "Streaming", color: "#9B59B6", icon: "🎵" },
    "social":    { label: "Social Media", color: "#E91E8C", icon: "📱" }
  },
  statusMeta: {
    "live":           { label: "Live",       color: "#00C851", icon: "✅" },
    "pending":        { label: "En attente", color: "#FFB300", icon: "⏳" },
    "unknown":        { label: "Inconnu",    color: "#9E9E9E", icon: "❓" },
    "not_applicable": { label: "N/A",        color: "#607D8B", icon: "—"  }
  },
  ecosystemColors: {
    "Spotify ecosystem":          "#1DB954",
    "Apple ecosystem":            "#A2AAAD",
    "YouTube / Google ecosystem": "#FF0000",
    "Amazon ecosystem":           "#00A8E0",
    "Alternatif":                 "#9B59B6",
    "Meta":                       "#E91E8C",
    "ByteDance":                  "#E91E8C"
  }
};
