// BibleChantée – Distribution mondiale – Données plateformes V2
// ⚠️ bibleChanteeUrl : à compléter manuellement plateforme par plateforme
// ⚠️ availabilityStatus : à confirmer — valeurs possibles : "live" | "pending" | "unknown" | "not_applicable"
window.distributionData = {
  platforms: [
    // ── SPOTIFY ECOSYSTEM ────────────────────────────────────────────────────────
    {
      id: "spotify",
      name: "Spotify",
      category: "streaming",
      ecosystem: "Spotify ecosystem",
      color: "#1DB954",
      region: "Global",
      lat: 59.3293, lng: 18.0686, city: "Stockholm",
      regions: ["Mondial"],
      icon: "🎵",
      officialUrl: "https://open.spotify.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    // ── APPLE ECOSYSTEM ──────────────────────────────────────────────────────────
    {
      id: "apple-music",
      name: "Apple Music",
      category: "streaming",
      ecosystem: "Apple ecosystem",
      color: "#A2AAAD",
      region: "Global",
      lat: 37.3346, lng: -122.0090, city: "Cupertino",
      regions: ["Mondial"],
      icon: "🍎",
      officialUrl: "https://music.apple.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    {
      id: "itunes",
      name: "iTunes",
      category: "streaming",
      ecosystem: "Apple ecosystem",
      color: "#A2AAAD",
      region: "Global",
      lat: 37.3346, lng: -122.0090, city: "Cupertino",
      regions: ["Mondial"],
      icon: "🍎",
      officialUrl: "https://www.apple.com/itunes/",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    // ── YOUTUBE / GOOGLE ECOSYSTEM ───────────────────────────────────────────────
    {
      id: "youtube-music",
      name: "YouTube Music",
      category: "streaming",
      ecosystem: "YouTube / Google ecosystem",
      color: "#FF0000",
      region: "Global",
      lat: 37.4220, lng: -122.0841, city: "Mountain View",
      regions: ["Mondial"],
      icon: "▶️",
      officialUrl: "https://music.youtube.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    // ── AMAZON ECOSYSTEM ─────────────────────────────────────────────────────────
    {
      id: "amazon-music",
      name: "Amazon Music",
      category: "streaming",
      ecosystem: "Amazon ecosystem",
      color: "#00A8E0",
      region: "Global",
      lat: 47.6062, lng: -122.3321, city: "Seattle",
      regions: ["Mondial"],
      icon: "📦",
      officialUrl: "https://music.amazon.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    // ── AUDIO STREAMING ALTERNATIF ───────────────────────────────────────────────
    {
      id: "deezer",
      name: "Deezer",
      category: "streaming",
      ecosystem: "Alternatif",
      color: "#9B59B6",
      region: "Europe / Global",
      lat: 48.8566, lng: 2.3522, city: "Paris",
      regions: ["Europe", "Monde"],
      icon: "🎧",
      officialUrl: "https://www.deezer.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    {
      id: "tidal",
      name: "Tidal",
      category: "streaming",
      ecosystem: "Alternatif",
      color: "#9B59B6",
      region: "Global",
      lat: 59.9139, lng: 10.7522, city: "Oslo",
      regions: ["Monde"],
      icon: "🎧",
      officialUrl: "https://tidal.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    {
      id: "iheartradio",
      name: "iHeartRadio",
      category: "streaming",
      ecosystem: "Alternatif",
      color: "#9B59B6",
      region: "USA",
      lat: 40.7128, lng: -74.0060, city: "New York",
      regions: ["USA"],
      icon: "📻",
      officialUrl: "https://www.iheart.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    {
      id: "pandora",
      name: "Pandora",
      category: "streaming",
      ecosystem: "Alternatif",
      color: "#9B59B6",
      region: "USA",
      lat: 37.8044, lng: -122.2712, city: "Oakland",
      regions: ["USA"],
      icon: "📻",
      officialUrl: "https://www.pandora.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    {
      id: "qobuz",
      name: "Qobuz",
      category: "streaming",
      ecosystem: "Alternatif",
      color: "#9B59B6",
      region: "Europe",
      lat: 48.8566, lng: 2.3522, city: "Paris",
      regions: ["Europe"],
      icon: "🎧",
      officialUrl: "https://www.qobuz.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    // ── SOCIAL MEDIA ─────────────────────────────────────────────────────────────
    {
      id: "instagram",
      name: "Instagram",
      category: "social",
      ecosystem: "Meta",
      color: "#E91E8C",
      region: "Global",
      lat: 37.4845, lng: -122.1477, city: "Menlo Park",
      regions: ["Mondial"],
      icon: "📸",
      officialUrl: "https://www.instagram.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    {
      id: "facebook",
      name: "Facebook",
      category: "social",
      ecosystem: "Meta",
      color: "#E91E8C",
      region: "Global",
      lat: 37.4845, lng: -122.1477, city: "Menlo Park",
      regions: ["Mondial"],
      icon: "👥",
      officialUrl: "https://www.facebook.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    {
      id: "tiktok",
      name: "TikTok",
      category: "social",
      ecosystem: "ByteDance",
      color: "#E91E8C",
      region: "Global",
      lat: 39.9042, lng: 116.4074, city: "Beijing",
      regions: ["Mondial"],
      icon: "🎵",
      officialUrl: "https://www.tiktok.com",
      bibleChanteeUrl: "",
      availabilityStatus: "unknown",
      notes: "",
      lastCheckedAt: ""
    },
    // ── PLATEFORMES RÉGIONALES CONFIRMÉES ────────────────────────────────────────
    {
      id: "boomplay",
      name: "Boomplay",
      category: "regional",
      ecosystem: "Afrique",
      color: "#FF8C00",
      region: "Afrique",
      lat: 6.5244, lng: 3.3792, city: "Lagos",
      regions: ["Afrique"],
      icon: "🌍",
      officialUrl: "https://www.boomplay.com",
      bibleChanteeUrl: "",
      availabilityStatus: "live",
      notes: "Présence confirmée",
      lastCheckedAt: ""
    }
    // ── PLATEFORMES RÉGIONALES À CONFIRMER (à décommenter le moment venu) ────────
    // { id: "anghami",      name: "Anghami",      category: "regional", ecosystem: "Moyen-Orient",      color: "#FF8C00", region: "MENA",               lat: 33.8938, lng:  35.5018, city: "Beyrouth",   regions: ["Moyen-Orient","Afrique du Nord"],  icon: "🌍", officialUrl: "https://www.anghami.com",         bibleChanteeUrl: "", availabilityStatus: "unknown", notes: "", lastCheckedAt: "" },
    // { id: "joox",         name: "Joox",         category: "regional", ecosystem: "Asie du Sud-Est",   color: "#FF8C00", region: "Asie du Sud-Est",    lat: 22.3193, lng: 114.1694, city: "Hong Kong",  regions: ["Asie du Sud-Est"],                icon: "🌏", officialUrl: "https://www.joox.com",            bibleChanteeUrl: "", availabilityStatus: "unknown", notes: "", lastCheckedAt: "" },
    // { id: "saavn",        name: "Saavn",        category: "regional", ecosystem: "Asie du Sud",       color: "#FF8C00", region: "Inde / Asie du Sud", lat: 19.0760, lng:  72.8777, city: "Mumbai",    regions: ["Inde","Asie du Sud"],             icon: "🌏", officialUrl: "https://www.jiosaavn.com",        bibleChanteeUrl: "", availabilityStatus: "unknown", notes: "", lastCheckedAt: "" },
    // { id: "netease",      name: "NetEase Music", category: "regional", ecosystem: "Chine",            color: "#FF8C00", region: "Chine",              lat: 30.2741, lng: 120.1551, city: "Hangzhou",  regions: ["Chine"],                          icon: "🌏", officialUrl: "https://music.163.com",           bibleChanteeUrl: "", availabilityStatus: "unknown", notes: "", lastCheckedAt: "" },
    // { id: "tencent-music",name: "Tencent Music",category: "regional", ecosystem: "Chine",            color: "#FF8C00", region: "Chine",              lat: 22.5431, lng: 114.0579, city: "Shenzhen",  regions: ["Chine"],                          icon: "🌏", officialUrl: "https://www.tencentmusic.com",    bibleChanteeUrl: "", availabilityStatus: "unknown", notes: "", lastCheckedAt: "" },
    // { id: "kuack",        name: "Kuack Media",  category: "regional", ecosystem: "Amérique Latine",  color: "#FF8C00", region: "Amérique Latine",    lat:  4.7110, lng: -74.0721, city: "Bogotá",    regions: ["Amérique Latine"],                icon: "🌎", officialUrl: "https://www.kuackmedia.com",       bibleChanteeUrl: "", availabilityStatus: "unknown", notes: "", lastCheckedAt: "" },
    // { id: "claro-musica", name: "Claro Música", category: "regional", ecosystem: "Amérique Latine",  color: "#FF8C00", region: "Amérique Latine",    lat: -12.0464, lng:-77.0428, city: "Lima",      regions: ["Amérique Latine"],                icon: "🌎", officialUrl: "https://www.claromusica.com",     bibleChanteeUrl: "", availabilityStatus: "unknown", notes: "", lastCheckedAt: "" },
    // { id: "flo",          name: "Flo",          category: "regional", ecosystem: "Corée du Sud",     color: "#FF8C00", region: "Corée du Sud",       lat: 37.5665, lng: 126.9780, city: "Séoul",     regions: ["Corée du Sud"],                   icon: "🌏", officialUrl: "https://www.music-flo.com",        bibleChanteeUrl: "", availabilityStatus: "unknown", notes: "", lastCheckedAt: "" },
    // { id: "adaptr",       name: "Adaptr",       category: "regional", ecosystem: "USA / B2B",        color: "#FF8C00", region: "USA",                lat: 40.7128, lng: -74.0060, city: "New York",  regions: ["USA"],                            icon: "🎵", officialUrl: "https://www.adaptr.com",          bibleChanteeUrl: "", availabilityStatus: "unknown", notes: "", lastCheckedAt: "" },
    // { id: "medianet",     name: "MediaNet",     category: "regional", ecosystem: "USA / B2B",        color: "#FF8C00", region: "USA",                lat: 32.7767, lng: -96.7970, city: "Dallas",    regions: ["USA"],                            icon: "🎵", officialUrl: "https://b2b.medianet.com",        bibleChanteeUrl: "", availabilityStatus: "unknown", notes: "", lastCheckedAt: "" }
  ],
  // ── META ──────────────────────────────────────────────────────────────────────
  categoryMeta: {
    "streaming": { label: "Streaming",   color: "#9B59B6", icon: "🎵" },
    "social":    { label: "Social Media", color: "#E91E8C", icon: "📱" },
    "regional":  { label: "Régional",    color: "#FF8C00", icon: "🌍" }
  },
  statusMeta: {
    "live":           { label: "Live",       color: "#00C851", icon: "✅" },
    "pending":        { label: "En attente", color: "#FFB300", icon: "⏳" },
    "unknown":        { label: "Inconnu",    color: "#9E9E9E", icon: "❓" },
    "not_applicable": { label: "N/A",        color: "#607D8B", icon: "—"  }
  },
  ecosystemColors: {
    "Spotify ecosystem":          "#1DB954",
    "Apple ecosystem":            "#A2AAAD",
    "YouTube / Google ecosystem": "#FF0000",
    "Amazon ecosystem":           "#00A8E0",
    "Alternatif":                 "#9B59B6",
    "Meta":                       "#E91E8C",
    "ByteDance":                  "#E91E8C",
    "Afrique":                    "#FF8C00"
  }
};
