// Bible Chantee - URLs MP3 Version 2
// Source: Google Drive (dossier public)
// Format URL: https://drive.google.com/uc?export=download&id=FILE_ID

const audioUrlsV2 = {
    // Genese - 50 chapitres (COMPLET)
    "01": {
        1: "https://drive.google.com/uc?export=download&id=1AIFKxvCUpF4sAgKgR4gCr4nhFiJo2HBL",
        2: "https://drive.google.com/uc?export=download&id=1j76vV6deaGFiQXlA3oyhE3Vzzx4ckjKX",
        3: "https://drive.google.com/uc?export=download&id=15TnB5Ef88km8ZxADuP_KWbK5HfxMVQRD",
        4: "https://drive.google.com/uc?export=download&id=13P1WxQ1-GaZjCpS4q87yc6X5Yix-Vk5X",
        5: "https://drive.google.com/uc?export=download&id=1z3mBpVyovTalY0_cEf1pArpJtLhCMWY2",
        6: "https://drive.google.com/uc?export=download&id=1VjJvGilNjELCtE4iy4wDxbql4SNzPsEx",
        7: "https://drive.google.com/uc?export=download&id=1Lqyh0FkMOHbJtp9JCOP_uAywep2plRzF",
        8: "https://drive.google.com/uc?export=download&id=1hQFUKMkwCLMaZHiw8E1IoNsFY-0hlnao",
        9: "https://drive.google.com/uc?export=download&id=1gl1dVl0Af9BM68HBGLs9lrxHZq5c-fAh",
        10: "https://drive.google.com/uc?export=download&id=1kMaGS26TTQSZGYYucOPsqmx1bOTNRUQs",
        11: "https://drive.google.com/uc?export=download&id=1JCsUCynT3VCHUCB-zDavIFUUpP4yFJwj",
        12: "https://drive.google.com/uc?export=download&id=1bTh-jym21bpXOOV8xM2OPOGxUHXtBeZV",
        13: "https://drive.google.com/uc?export=download&id=1iE_Oh0XBD0gqmNZhysiKWolbp5QzVUsZ",
        14: "https://drive.google.com/uc?export=download&id=1MgXPdQ48ix4rM8pi53EhQrnAv2Dfe_xX",
        15: "https://drive.google.com/uc?export=download&id=1crnOni8z95CqU7_jKjXA9hJO_E5TmSIo",
        16: "https://drive.google.com/uc?export=download&id=1MrQFyt7uKM82V7wc5bYLFt38a-979cIC",
        17: "https://drive.google.com/uc?export=download&id=1Gksh1Bn1Cup6A49xeqPWN1Feyes_Ka78",
        18: "https://drive.google.com/uc?export=download&id=1XpxwyKN8x0w3M8gw1Kpz8K6sASxwwZl2",
        19: "https://drive.google.com/uc?export=download&id=1NPV_dYLppd0kFBoGwCbDpDsb1723DO3P",
        20: "https://drive.google.com/uc?export=download&id=1snlIY5JKQ0AWZ6wWxwuRIM1QznSyXhan",
        21: "https://drive.google.com/uc?export=download&id=1fptZy0BisfUVai6nmiPJZpVk9gVukwOM",
        22: "https://drive.google.com/uc?export=download&id=1vIa0MVmYlCDOltjsuTS2xRkTWOGyTQ1s",
        23: "https://drive.google.com/uc?export=download&id=1Kwf2K2CC2xE4hTDHNyFO_YEpeo3zQxoQ",
        24: "https://drive.google.com/uc?export=download&id=1uby-xdHjAFBakvPUcmaAaKU6OjtJolRM",
        25: "https://drive.google.com/uc?export=download&id=1Vgs-2HKmMDIQ0CjF7Ndds2axZOqCI9zZ",
        26: "https://drive.google.com/uc?export=download&id=10VCPBx7NfwlLCvfX1c8xhM76M3l8l53A",
        27: "https://drive.google.com/uc?export=download&id=1y-gG0OGUITlYbv3YBDYgohKsg6l-UeyB",
        28: "https://drive.google.com/uc?export=download&id=1eB1IBha8sjs_fXXxqMZiJW6wBsH5iAa0",
        29: "https://drive.google.com/uc?export=download&id=1AxuAFWN1flqSEIx9O2fZuz_r76Vq_a_m",
        30: "https://drive.google.com/uc?export=download&id=1_Igd9OpZ28JHLV5rR4yCBIX66FhlVAa-",
        31: "https://drive.google.com/uc?export=download&id=1ZUa8GbigdQP8OlG7HU5ROTQYOfklJKS0",
        32: "https://drive.google.com/uc?export=download&id=1T5kOPHfovSt0SD2q_6kaTKMGO52DYM4Y",
        33: "https://drive.google.com/uc?export=download&id=1KvSpKGipXZxzKfTlLkB3ocWhDfHWIofb",
        34: "https://drive.google.com/uc?export=download&id=164rtZohS6y8b-HVRuezgH6ZQqwiLczOC",
        35: "https://drive.google.com/uc?export=download&id=10rr1LbFiWhbAR5YUPVJQttm7WX4lG-HU",
        36: "https://drive.google.com/uc?export=download&id=1cKUb3BuykbLWUC_1genaq7mQZZh5KdRw",
        37: "https://drive.google.com/uc?export=download&id=10EWLdA-pAMJ3_agpvQUZ0F1or2KI7VcD",
        38: "https://drive.google.com/uc?export=download&id=1qqUiUx6prj-dzPBcU_-BfQYBA5fg6FRT",
        39: "https://drive.google.com/uc?export=download&id=1nV2yRHesgB0qY8wivZDiRaguv4GmOGrn",
        40: "https://drive.google.com/uc?export=download&id=137rTTeGccYCl96v58Nu-ks5vV5EZv1BU",
        41: "https://drive.google.com/uc?export=download&id=1roPtUIi3QEdqrg2Q0uvq15qJkoKD2ScC",
        42: "https://drive.google.com/uc?export=download&id=1QHggbdD3wIN1586ot_qw8rXk3iLqMycW",
        43: "https://drive.google.com/uc?export=download&id=1JVJZebJbRlk8Uwp-JFcibx5jFlJOdU_M",
        44: "https://drive.google.com/uc?export=download&id=1LP-DDf0tciFL-Oklv3z1qW-VluQ4z2cF",
        45: "https://drive.google.com/uc?export=download&id=1NfFuhL2v9zsYJ6xkTB5zlqL_Ucp6Nws-",
        46: "https://drive.google.com/uc?export=download&id=14IaZ_f5xEhB2NWsYyu3Ug_JU11m2jF2q",
        47: "https://drive.google.com/uc?export=download&id=1DWhrSfxBapxs1zGl4tDYxP283Ce5U3be",
        48: "https://drive.google.com/uc?export=download&id=1m0YhrvijWuILnb8LhYz3D3g7PHCb1025",
        49: "https://drive.google.com/uc?export=download&id=1-shx9ZrS_94Kk85sPrw7YOQcjKxdQmcv",
        50: "https://drive.google.com/uc?export=download&id=1KMAccC0mXm-VtiPUreHH-poNDSb2zkjy"
    },
    
    // Exode - 40 chapitres (COMPLET)
    "02": {
        1: "https://drive.google.com/uc?export=download&id=1yiqnuZkHHPCVY9R8anmu4KmH5zhW-Cw6",
        2: "https://drive.google.com/uc?export=download&id=14A5YG_mARA5Be9zHnvoUWq0WXQ8tlX15",
        3: "https://drive.google.com/uc?export=download&id=1D6BRiugY_Cp5LHvQytiERHMqaOdakW3k",
        4: "https://drive.google.com/uc?export=download&id=1KdezXC3XmNHIzddfp5K3FOs_TzAo1uSc",
        5: "https://drive.google.com/uc?export=download&id=1m82CZdB0DrhFIB04nmSWcK-fGfMik5YC",
        6: "https://drive.google.com/uc?export=download&id=1QnXbgICNZKyJk3DJlo-h84Gw99R862-A",
        7: "https://drive.google.com/uc?export=download&id=1R3mMDaL9NdGBmHY0sLzY2emIfsRoeOxC",
        8: "https://drive.google.com/uc?export=download&id=11RHFQ7hJkfTBNi2UEFsM8KwUc-P8LCwG",
        9: "https://drive.google.com/uc?export=download&id=1tRH6fnYCKvHbZ85F7w72HdSLIqcKYGGX",
        10: "https://drive.google.com/uc?export=download&id=1uQ_XyYfmBS_30GSwyfTADmH9F-GUIb5N",
        11: "https://drive.google.com/uc?export=download&id=1Cwwlpoz4FYx6BgXsztzRdS7cEW6mdqNR",
        12: "https://drive.google.com/uc?export=download&id=1EkNRK3wo1bfedg0QlBo7hcpa-hIbz-ob",
        13: "https://drive.google.com/uc?export=download&id=13-6Xvi1LgKdBscjwgqWZHXMKq2msJ5h6",
        14: "https://drive.google.com/uc?export=download&id=1MpbLqPStlhwnawS7g3gmQZ_SgkdM8ks6",
        15: "https://drive.google.com/uc?export=download&id=1_hFIhf3tL2IKuPOZ-ECbmrJXPSZvcVVQ",
        16: "https://drive.google.com/uc?export=download&id=1dVWvkYUQHvGtpcQpf3AJNdhrKzByJku6",
        17: "https://drive.google.com/uc?export=download&id=1h4bq3YGaWuWvxnzChj5RyNLMEF1pCWbF",
        18: "https://drive.google.com/uc?export=download&id=1WwHiiSt_rbC-PlPQKeZPS-Li-3dFqk1K",
        19: "https://drive.google.com/uc?export=download&id=10He-8587Yw1cWDyFzMsakOPeEUNGNj25",
        20: "https://drive.google.com/uc?export=download&id=1jcjd0LqUj9PeYx08GeLSOjIbHrFuLfZi",
        21: "https://drive.google.com/uc?export=download&id=1uunmPU_bhgC0OKqbJzcbC7q2MBNdMkIo",
        22: "https://drive.google.com/uc?export=download&id=1yT6UyksXpMjYV_XkxmQibnoZS3uNtxUL",
        23: "https://drive.google.com/uc?export=download&id=1zSLJqJtXla8XDqZbsASqFaW-OA_0tdr8",
        24: "https://drive.google.com/uc?export=download&id=15xZLE9VhYiwBD2e9h-xCYG_ySEHMBorX",
        25: "https://drive.google.com/uc?export=download&id=14Yv8Hv93uwJvOh9ciNJNSyMumiONBFwv",
        26: "https://drive.google.com/uc?export=download&id=1R5awb3e3Cl2dn2VN0j71tI7b4r8vdzVJ",
        27: "https://drive.google.com/uc?export=download&id=1LA4wEo6hoKy5wBJvECCHCGRvRSislPrb",
        28: "https://drive.google.com/uc?export=download&id=1OW-f0HXMkIS2U63ct96pfPrcYr_XhtU7",
        29: "https://drive.google.com/uc?export=download&id=101795-8ZWllaxJgqoBoLD-7YnCEZYh6m",
        30: "https://drive.google.com/uc?export=download&id=1dyr5quBxVaAgL2vJZ_OeRO59LQwnBFIk",
        31: "https://drive.google.com/uc?export=download&id=1gGWNeq8vxe6znNT2pnSr21FCiGXKYLXT",
        32: "https://drive.google.com/uc?export=download&id=1nH9x5B-FA3lJRd8Z-3i8GoK23NWJMS7p",
        33: "https://drive.google.com/uc?export=download&id=1qXxN8-YuVUafWNfSehtJfF3hQh5uvq9V",
        34: "https://drive.google.com/uc?export=download&id=1myRVWysg9uoN6nZs-Rf7HXLWbC5WwoGe",
        35: "https://drive.google.com/uc?export=download&id=1ppNddLNAyHmxEq8_QdcKKn00jpnKAdhL",
        36: "https://drive.google.com/uc?export=download&id=1R2_914cVnDpr0pjaOpXqNWseslU344O5",
        37: "https://drive.google.com/uc?export=download&id=1NFN_QC-91u8ufYKYH3n9-RadPptqAVRS",
        38: "https://drive.google.com/uc?export=download&id=18paUbA7O1dRHqe---51mkqDp9M9Bv6VF",
        39: "https://drive.google.com/uc?export=download&id=18_atfN_XSHCRbJj_D5bprkrp-JuVH-H_",
        40: "https://drive.google.com/uc?export=download&id=1lITJgbahCgyCagarJ9jj2TW0isnWJVmB"
    }
};
