name: CI

on:
  push:
    branches: [ "prod", "main" ]
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run audit
        shell: pwsh
        run: |
          pwsh -NoProfile -Command "./RUN_AUDIT.ps1"
